
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["PXL", "dacincubator"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["KBY", "dacincubator"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["TPT", "tokendapppub"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["PUB", "tokendapppub"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["ADD", "eosadddddddd"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["ATD", "eosatidiumio"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["BLACK", "eosblackteam"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["BOID", "boidcomtoken"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["BTN", "eosbuttonbtn"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["CAN", "eoscancancan"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["CAT", "tokenbyeocat"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["CET", "eosiochaince"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["CHL", "challengedace"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["DAB", "eoscafekorea"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["DICE", "betdicetoken"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["EDNA", "ednazztokens"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["EOSDAC", "eosdactokens"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["EOSNTS", "eosninetiess"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["EOX", "eoxeoxeoxeox"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["EPRA", "epraofficial"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["ESB", "esbcointoken"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["EVR", "eosvrtokenss"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["FAID", "eosfaidchain"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["HOURS", "horustokenio"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["IQ", "everipediaiq"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["ITECOIN", "itecointoken"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["KARMA", "therealkarma"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["LKY", "bkyyshayysha"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["LUCK", "eosluckchain"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["LUCKY", "eoslucktoken"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["MEETONE", "eosiomeetone"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["MORE", "eosiomoreone"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["OCT", "octtothemoon"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["PGL", "prospectorsg"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["PIXEL", "1pixelmaster"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["POOR", "poormantoken"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["PSO", "cryptopesosc"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["PXL", "dacincubator"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["ROY", "eosroyaleroy"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["SEVEN", "xxxsevensxxx"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["SHAPE", "gmaslaunches"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["TEA", "linzongsheng"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["TOE", "talkoneos123"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["TRYBE", "trybenetwork"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["WECASH", "weosservices"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["WIZBOX", "wizboxairdro"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '["WIZZ", "wizznetwork1"]' -p kyubeydex.bp@active
cleos -u http://api-direct.eosasia.one push action kyubeydex.bp setwhitelist '[""YOU, "youbaoyoubao"]' -p kyubeydex.bp@active

cleos -u http://api-direct.eosasia.one get table kyubeydex.bp KBY whitelist